-- Create the 'users' table
CREATE TABLE "users" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL
);
-- Create the 'orders' table
CREATE TABLE orders (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INT NOT NULL,
    "order_date" DATE NOT NULL,
    "total_amount" DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY ("user_id") REFERENCES "users"("id")
);